# Generated by Django 5.2.6 on 2026-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('TRUCK', 'Truck'), ('BUS', 'Bus')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('mileage', models.FloatField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('purchase_date', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
